name: pgvector
description: pgvector support for Dart.
version: 0.2.0
repository: https://github.com/pgvector/pgvector-dart

environment:
  sdk: ^3.0.0

dependencies:
  postgres: ^3.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
